Feature/database
Arthelh/NCNF pull request #60
Opened 2021-03-24 20:38 UTC by Jnf14

Required coverage percentage not achieved yet, but big feature to merge.

2021-03-25 19:13 UTC, Arthelh requested changes
Enlevez le fichier google-services.json du git. Et, ligne 12 de ce fichier, est-ce qu'il faudrait pas mettre "package_name": "com.ncnf" plutôt?

2021-03-25 19:21 UTC, Jnf14 commented
> Enlevez le fichier google-services.json du git.

Pas besoin pour cirrus ? Il y a tout ce qui est Firebase là dedans !

 >Et, ligne 12 de ce fichier, est-ce qu'il faudrait pas mettre "package_name": "com.ncnf" plutôt?

Si tu regardes plus bas on a une autre app qui tourne sur Firebase avec l'ancien nom. On ne l'a pas encore supprimé "Au cas où".

2021-03-25 19:42 UTC, Arthelh approved these changes

2021-03-25 20:11 UTC, HyPn0TiiK approved these changes

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/java/com/ncnf/user/PrivateUser.java
> +    private DatabaseServiceInterface db;
Make attributes final

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/java/com/ncnf/user/UserProfileActivity.java
> +    EditText email;
make attributes private and final (except for booleans)

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Profile"
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Disconnected"
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_main.xml
>          android:text="FeedView"
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_user_profile.xml
> +        android:text="Log Out"
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_user_profile.xml
> +        android:text="Welcome to your Profile"
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_user_profile.xml
> +        android:hint="Email Address"
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_user_profile.xml
> +        android:hint="Firstname..."
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_user_profile.xml
> +        android:hint="Date of birth..."
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_user_profile.xml
> +        android:hint="Lastname..."
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/activity_user_profile.xml
> +        android:text="Save"
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/fragment_sign_in.xml
> +<?xml version="1.0" encoding="utf-8"?>
Make text refer to a string in res/value with @string

2021-03-25 20:11 UTC, HyPn0TiiK commented on app/src/main/res/layout/fragment_sign_up.xml
> +<?xml version="1.0" encoding="utf-8"?>
Make text refer to a string in res/value with @string

2021-03-26 09:03 UTC, Arthelh approved these changes

2021-03-26 10:30 UTC, merged